apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: ingress-controller
  name: root-url-tls
spec:
  secretName: taskcluster-ingress-tls-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  # hostname is root_url without the 'https://' (8 characters)
  commonName: {$eval: 'root_url[8:]'}
  acme:
    config:
    - http01:
        ingress: certificate-challenge-ingress
      domains:
      - {$eval: 'root_url[8:]'}
