apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: ingress-controller
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: taskcluster-accounts@mozilla.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-issuer-privkey

    http01: {}
