apiVersion: v1
kind: Secret
type: Opaque
metadata:
  # this must be the same namespace as the controller itself
  namespace: ingress-controller
  name: taskcluster-ingress-tls-secret
data:
  tls.crt: ${base64encode(tls_crt)}
  tls.key: ${base64encode(tls_key)}
