# From https://github.com/jetstack/cert-manager/blob/v0.5.2/contrib/manifests/cert-manager/with-rbac.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "cert-manager"
  labels:
    name: "cert-manager"
    certmanager.k8s.io/disable-validation: "true"
