# From https://github.com/jetstack/cert-manager/blob/v0.5.0/contrib/manifests/cert-manager/with-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: "cert-manager"
  labels:
    app: cert-manager
    chart: cert-manager-v0.5.0
    release: cert-manager
    heritage: Tiller
